// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzU5HVmxImpaxJnN_xgfQc296lAouNNco',
    appId: '1:923528477101:web:ae9381dbc0732c32c74924',
    messagingSenderId: '923528477101',
    projectId: 'amar-final',
    authDomain: 'amar-final.firebaseapp.com',
    storageBucket: 'amar-final.firebasestorage.app',
    measurementId: 'G-TCFMM1S0YB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARUzuVdRncnLtP8tAFBVHCmcB8unMgfek',
    appId: '1:923528477101:android:bf3f87760f37216cc74924',
    messagingSenderId: '923528477101',
    projectId: 'amar-final',
    storageBucket: 'amar-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMxENRWcmrGApTJNXwILNzEwr6NwcI7LA',
    appId: '1:923528477101:ios:f90ae73e21996752c74924',
    messagingSenderId: '923528477101',
    projectId: 'amar-final',
    storageBucket: 'amar-final.firebasestorage.app',
    iosBundleId: 'com.example.amarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMxENRWcmrGApTJNXwILNzEwr6NwcI7LA',
    appId: '1:923528477101:ios:f90ae73e21996752c74924',
    messagingSenderId: '923528477101',
    projectId: 'amar-final',
    storageBucket: 'amar-final.firebasestorage.app',
    iosBundleId: 'com.example.amarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzU5HVmxImpaxJnN_xgfQc296lAouNNco',
    appId: '1:923528477101:web:17572d892660100fc74924',
    messagingSenderId: '923528477101',
    projectId: 'amar-final',
    authDomain: 'amar-final.firebaseapp.com',
    storageBucket: 'amar-final.firebasestorage.app',
    measurementId: 'G-XK8PNBB2YN',
  );
}
